# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/GIGABYTE/Downloads/TKLL_NHOM11-sunsik_every_except_STO/TKLL_NHOM11-sunsik_every_except_STO/doan/project_ANH_NGHI.runs/synth_1/RISC_CPU.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/GIGABYTE/Downloads/TKLL_NHOM11-sunsik_every_except_STO/TKLL_NHOM11-sunsik_every_except_STO/doan/project_ANH_NGHI.cache/wt [current_project]
set_property parent.project_path C:/Users/GIGABYTE/Downloads/TKLL_NHOM11-sunsik_every_except_STO/TKLL_NHOM11-sunsik_every_except_STO/doan/project_ANH_NGHI.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/GIGABYTE/Downloads/TKLL_NHOM11-sunsik_every_except_STO/TKLL_NHOM11-sunsik_every_except_STO/doan/project_ANH_NGHI.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  C:/Users/GIGABYTE/Downloads/TKLL_NHOM11-sunsik_every_except_STO/TKLL_NHOM11-sunsik_every_except_STO/doan/project_ANH_NGHI.srcs/sources_1/new/data_init.mem
  C:/Users/GIGABYTE/Downloads/TKLL_NHOM11-sunsik_every_except_STO/TKLL_NHOM11-sunsik_every_except_STO/doan/project_ANH_NGHI.srcs/sources_1/new/instruction_file.mem
}
read_verilog -library xil_defaultlib {
  C:/Users/GIGABYTE/Downloads/TKLL_NHOM11-sunsik_every_except_STO/TKLL_NHOM11-sunsik_every_except_STO/doan/project_ANH_NGHI.srcs/sources_1/new/ALU.v
  C:/Users/GIGABYTE/Downloads/TKLL_NHOM11-sunsik_every_except_STO/TKLL_NHOM11-sunsik_every_except_STO/doan/project_ANH_NGHI.srcs/sources_1/new/Accumulator_Register.v
  C:/Users/GIGABYTE/Downloads/TKLL_NHOM11-sunsik_every_except_STO/TKLL_NHOM11-sunsik_every_except_STO/doan/project_ANH_NGHI.srcs/sources_1/new/Controller.v
  C:/Users/GIGABYTE/Downloads/TKLL_NHOM11-sunsik_every_except_STO/TKLL_NHOM11-sunsik_every_except_STO/doan/project_ANH_NGHI.srcs/sources_1/new/Instruction_Register.v
  C:/Users/GIGABYTE/Downloads/TKLL_NHOM11-sunsik_every_except_STO/TKLL_NHOM11-sunsik_every_except_STO/doan/project_ANH_NGHI.srcs/sources_1/new/Program_Counter.v
  C:/Users/GIGABYTE/Downloads/TKLL_NHOM11-sunsik_every_except_STO/TKLL_NHOM11-sunsik_every_except_STO/doan/project_ANH_NGHI.srcs/sources_1/new/addr_mux.v
  C:/Users/GIGABYTE/Downloads/TKLL_NHOM11-sunsik_every_except_STO/TKLL_NHOM11-sunsik_every_except_STO/doan/project_ANH_NGHI.srcs/sources_1/new/dataMemory.v
  C:/Users/GIGABYTE/Downloads/TKLL_NHOM11-sunsik_every_except_STO/TKLL_NHOM11-sunsik_every_except_STO/doan/project_ANH_NGHI.srcs/sources_1/new/instructionMemory.v
  C:/Users/GIGABYTE/Downloads/TKLL_NHOM11-sunsik_every_except_STO/TKLL_NHOM11-sunsik_every_except_STO/doan/project_ANH_NGHI.srcs/sources_1/new/RISC_CPU.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/DA_TKLL/Arty-Z7-20-Extension-board-Master.xdc
set_property used_in_implementation false [get_files F:/DA_TKLL/Arty-Z7-20-Extension-board-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/GIGABYTE/Downloads/TKLL_NHOM11-sunsik_every_except_STO/TKLL_NHOM11-sunsik_every_except_STO/doan/project_ANH_NGHI.srcs/utils_1/imports/synth_1/RISC_CPU.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top RISC_CPU -part xc7z020clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RISC_CPU.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file RISC_CPU_utilization_synth.rpt -pb RISC_CPU_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
